"""Live teacher, read-only feeds, and queued local conversations."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import time
import uuid

from .pathway_live import CHANNELS, TERMINAL_STATES, LiveEventBus, _safe_write_json
from .terminal import configure_utf8_output


class TrainingLock:
    """An OS-released lock prevents two local wave trainers competing for CPU."""

    def __init__(self, path: Path) -> None:
        self.path = path

    def __enter__(self):
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.stream = self.path.open("a+b")
        self.stream.write(b"0")
        self.stream.flush()
        self.stream.seek(0)
        try:
            import msvcrt
            msvcrt.locking(self.stream.fileno(), msvcrt.LK_NBLCK, 1)
        except ImportError:
            import fcntl
            fcntl.flock(self.stream.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except OSError:
            self.stream.close()
            raise RuntimeError("Another Kavi wave trainer is already running.") from None
        return self

    def __exit__(self, *args):
        self.stream.close()


def safe_display(value: str) -> str:
    return "".join(c if ord(c) >= 32 or c in "\n\t" else f"\\x{ord(c):02x}" for c in value)


def status(root: Path) -> dict:
    path = root / "status.json"
    try:
        return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"state": "starting"}
    except (OSError, ValueError):
        return {"state": "updating"}


def watch(root: Path, channel: str) -> None:
    path = root / f"{channel}.jsonl"
    offset, pending = 0, b""
    print(f"Kavi live {channel} — {root}\nWaiting for real events...", flush=True)
    while True:
        if path.exists():
            with path.open("rb") as stream:
                stream.seek(offset)
                pending += stream.read()
                offset = stream.tell()
            rows = pending.split(b"\n")
            pending = rows.pop()
            for row in rows:
                if not row:
                    continue
                event = json.loads(row)
                if event.get("kind") == "stream-token":
                    print(safe_display(event["text"]), end="", flush=True)
                else:
                    print(safe_display(event.get("display", json.dumps(event))), flush=True)
        if status(root).get("state") in TERMINAL_STATES:
            print("\nTeacher ended. These are saved real results, not an active training animation.")
            return
        time.sleep(0.15)


def enqueue(root: Path, question: str, answer: str | None = None, explanation: str = "") -> Path:
    if status(root).get("state") in TERMINAL_STATES:
        raise ValueError("This run has ended; resume it before sending a new question.")
    if not question or len(question.encode()) > 3000 or len(((answer or "") + explanation).encode()) > 8000:
        raise ValueError("Question/correction is empty or exceeds the interaction budget.")
    inbox = root / "inbox"
    inbox.mkdir(parents=True, exist_ok=True)
    path = inbox / f"{time.time_ns()}-{uuid.uuid4().hex}.json"
    _safe_write_json(path, {"question": question, "answer": answer, "explanation": explanation,
                            "provenance": "owner-supplied-observation-or-correction"})
    return root / "responses" / path.name


def console(root: Path) -> None:
    print("Kavi conversation and controls\n"
          "Type a question. It is answered, then learned as unverified input.\n"
          "Correct it: /teach question => answer || explanation\n"
          "Controls: /status, /pause, /resume, /stop, /quit\n"
          "The Answers tab streams each generated byte. /quit closes only this console.\n"
          "Conversation text is kept in local run logs, never posted online.", flush=True)
    while True:
        try:
            message = input("\nYou> ").strip()
        except (EOFError, KeyboardInterrupt):
            return
        if not message:
            continue
        if message == "/quit":
            return
        if message == "/status":
            print(json.dumps(status(root), indent=2))
            continue
        if message in {"/pause", "/resume", "/stop"}:
            from .pathway_cli import _signal
            _signal(root, message[1:])
            continue
        answer, explanation = None, ""
        if message.startswith("/teach "):
            try:
                question, correction = message[7:].split("=>", 1)
                bits = correction.split("||", 1)
                answer = bits[0].strip()
                explanation = bits[1].strip() if len(bits) > 1 else "User-supplied correction."
                message = question.strip()
            except ValueError:
                print("Use /teach question => correct answer || explanation")
                continue
        try:
            response = enqueue(root, message, answer, explanation)
            print(f"Queued. Live answer appears in Answers; response file: {response}")
        except ValueError as error:
            print(str(error))


def main(argv: list[str] | None = None) -> int:
    configure_utf8_output()
    parser = argparse.ArgumentParser(description="Kavi original-book learning and live conversations")
    sub = parser.add_subparsers(dest="command", required=True)
    run = sub.add_parser("run")
    run.add_argument("--run-dir", type=Path, required=True)
    run.add_argument("--foundation", type=Path, required=True)
    run.add_argument("--resume", type=Path)
    run.add_argument("--max-rounds", type=int, default=12)
    run.add_argument("--exam-cases", type=int, default=32)
    run.add_argument("--practice-cases", type=int, default=32)
    run.add_argument("--max-seconds", type=int, default=86400)
    run.add_argument("--keep-available", action="store_true")
    run.add_argument("--multilingual-bridge", action="store_true")
    for name in ("watch", "console"):
        command = sub.add_parser(name)
        command.add_argument("--run-dir", type=Path, required=True)
        if name == "watch":
            command.add_argument("--channel", choices=CHANNELS, required=True)
    args = parser.parse_args(argv)
    root = args.run_dir.resolve()
    if args.command == "watch":
        watch(root, args.channel)
        return 0
    if args.command == "console":
        console(root)
        return 0
    repo = Path(__file__).resolve().parents[1]
    if not root.is_relative_to(repo / "runs"):
        parser.error("Run directory must be inside this repository's ignored runs directory.")
    bus = None
    runtime = None
    try:
        with TrainingLock(repo / "runs/.wave-training.lock"):
            bus = LiveEventBus(root)
            from .continuous_teacher import TeachingConfig
            from .language_teacher import LanguageFirstTeacher
            config = TeachingConfig(root, args.foundation.resolve(),
                                    args.resume.resolve() if args.resume else None,
                                    max_rounds=args.max_rounds, exam_cases=args.exam_cases,
                                    practice_cases=args.practice_cases,
                                    max_seconds=args.max_seconds, keep_available=args.keep_available)
            if args.multilingual_bridge:
                from .multilingual_bridge import MultilingualBridgeTeacher
                runtime = MultilingualBridgeTeacher(repo, config, bus)
            else:
                runtime = LanguageFirstTeacher(repo, config, bus)
            print(f"Kavi teacher running.\nRun: {root}\nFollow the Teaching/Answers/Pathways/Learning/Grading tabs.", flush=True)
            print(json.dumps(runtime.run(), indent=2))
            return 0
    except KeyboardInterrupt:
        if bus:
            bus.update_status("stopped", detail="Interrupted from the console; resume the last atomic checkpoint.")
        return 130
    except Exception as error:
        if runtime is not None:
            try:
                runtime.save("exception-recovery")
            except Exception as checkpoint_error:
                print(f"Emergency checkpoint also failed: {checkpoint_error}", flush=True)
        if bus:
            bus.emit("lessons", "failure", display=f"Teacher failed: {type(error).__name__}: {error}")
            bus.update_status("failed", detail=str(error))
        raise


if __name__ == "__main__":
    raise SystemExit(main())
